# Generated by Django 4.1.7 on 2024-01-03 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Historical_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='image')),
                ('Name', models.CharField(max_length=50)),
                ('Address', models.TextField(max_length=100)),
                ('Rating', models.IntegerField(max_length=10000000)),
                ('Location', models.CharField(max_length=1000)),
            ],
        ),
    ]
