# Generated by Django 4.1.7 on 2024-01-23 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Historical_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(blank=True, null=True, upload_to='image')),
                ('Place_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Wikipedia', models.TextField(blank=True, max_length=100000000, null=True)),
                ('Section_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Section_Image', models.ImageField(blank=True, null=True, upload_to='image')),
            ],
        ),
    ]
