# Generated by Django 4.1.7 on 2024-01-23 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Historical_app', '0002_place_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='place_detail',
            name='H_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Historical_app.historical_data'),
        ),
    ]
