# Generated by Django 4.1.7 on 2024-01-25 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Historical_app', '0003_place_detail_h_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place_detail',
            name='Section_Image',
        ),
        migrations.CreateModel(
            name='Place_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Section_Image', models.ImageField(blank=True, null=True, upload_to='image')),
                ('ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Historical_app.place_detail')),
            ],
        ),
    ]
