# Generated by Django 4.1.7 on 2024-01-25 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Historical_app', '0004_remove_place_detail_section_image_place_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place_image',
            old_name='ID',
            new_name='PlaceId',
        ),
    ]
