# Generated by Django 4.1.7 on 2024-01-29 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Historical_app', '0005_rename_id_place_image_placeid'),
    ]

    operations = [
        migrations.AddField(
            model_name='place_detail',
            name='Wikipedia_Link',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
